import type {
  ImportedProject,
  VerifiedCapture,
} from "./App";

const verifiedEvidence: Pick<
  VerifiedCapture,
  | "evidenceLevel"
  | "sourceRevision"
  | "runtimeEvidence"
  | "validationResult"
> = {
  evidenceLevel: "verified",
  sourceRevision: "fixture@abc123",
  runtimeEvidence: "Fixture runtime reproduced",
  validationResult: "passed",
};

export const demoProject: ImportedProject = {
  id: "northstar-commerce",
  title: "Northstar Commerce",
  status: "Imported",
  coverage: {
    requiredCaptureIds: [
      "dashboard-desktop",
      "dashboard-tablet",
      "dashboard-mobile",
      "checkout-desktop",
      "checkout-tablet",
      "checkout-mobile",
    ],
  },
  screens: [
    {
      id: "dashboard-default",
      name: "Dashboard",
      route: "/dashboard",
      state: "Default",
      captures: [
        {
          id: "dashboard-desktop",
          viewport: "desktop",
          label: "Desktop",
          dimensions: "1440 × 900",
          coverageHealth: "current",
          frameKind: "CodeFrame",
          sourceAnchor: "src/screens/Dashboard.tsx:24",
          ...verifiedEvidence,
        },
        {
          id: "dashboard-tablet",
          viewport: "tablet",
          label: "Tablet",
          dimensions: "834 × 1112",
          coverageHealth: "current",
          frameKind: "CodeFrame",
          sourceAnchor: "src/screens/Dashboard.tsx:24",
          ...verifiedEvidence,
        },
        {
          id: "dashboard-mobile",
          viewport: "mobile",
          label: "Mobile",
          dimensions: "390 × 844",
          coverageHealth: "current",
          frameKind: "CodeFrame",
          sourceAnchor: "src/screens/Dashboard.tsx:24",
          ...verifiedEvidence,
        },
      ],
    },
    {
      id: "checkout-validation-error",
      name: "Checkout",
      route: "/checkout",
      state: "Validation error",
      captures: [
        {
          id: "checkout-desktop",
          viewport: "desktop",
          label: "Desktop",
          dimensions: "1440 × 900",
          coverageHealth: "current",
          frameKind: "CodeFrame",
          evidenceLevel: "verified",
          sourceRevision: "fixture@abc123",
          sourceAnchor: "src/screens/Checkout.tsx:88",
          runtimeEvidence: "Validation-error fixture reproduced",
          validationResult: "passed",
        },
        {
          id: "checkout-tablet",
          viewport: "tablet",
          label: "Tablet",
          dimensions: "834 × 1112",
          coverageHealth: "blocked",
          blocker: "Fixture for validation state is unavailable",
          attemptedEvidence: "Route discovery and isolated preview startup",
        },
        {
          id: "checkout-mobile",
          viewport: "mobile",
          label: "Mobile",
          dimensions: "390 × 844",
          coverageHealth: "partial",
          frameKind: "CodeFrame",
          evidenceLevel: "observed",
          missingEvidence: "Current source anchor and validation result",
        },
      ],
    },
  ],
  selectedCaptureId: "checkout-desktop",
  task: {
    id: "task-mobile-checkout",
    title: "Correct checkout spacing",
    status: "Awaiting approval",
    harness: "codex",
    harnesses: [
      { id: "codex", label: "Codex" },
      { id: "claude", label: "Claude" },
    ],
  },
  trace: [
    {
      id: "trace-context",
      type: "context",
      status: "complete",
      actorKind: "human",
      actor: "Sarvesh",
      action: "Attached Checkout · Desktop",
      timestamp: "10:42:01",
      targetCaptureId: "checkout-desktop",
      targetLabel: "Checkout · Desktop",
    },
    {
      id: "trace-routing",
      type: "routing",
      status: "complete",
      actorKind: "human",
      actor: "Sarvesh",
      action: "Selected Codex harness",
      timestamp: "10:42:03",
      harness: "Codex",
      targetCaptureId: "checkout-desktop",
      targetLabel: "Checkout · Desktop",
    },
    {
      id: "trace-task",
      type: "task",
      status: "complete",
      actorKind: "agent",
      actor: "Codex",
      action: "Started task",
      timestamp: "10:42:04",
      harness: "Codex",
      targetCaptureId: "checkout-desktop",
      targetLabel: "Checkout · Desktop",
    },
    {
      id: "trace-plan",
      type: "plan",
      status: "complete",
      actorKind: "agent",
      actor: "Codex",
      action: "Published plan",
      timestamp: "10:42:06",
      harness: "Codex",
      targetCaptureId: "dashboard-tablet",
      targetLabel: "Dashboard · Tablet",
    },
    {
      id: "trace-proposal",
      type: "proposal",
      status: "complete",
      actorKind: "agent",
      actor: "Codex",
      action: "Created spacing proposal",
      timestamp: "10:42:08",
      harness: "Codex",
      targetCaptureId: "checkout-desktop",
      targetLabel: "Checkout · Desktop",
    },
    {
      id: "trace-approval",
      type: "approval",
      status: "waiting",
      actorKind: "system",
      actor: "Memi",
      action: "Requested approval",
      timestamp: "10:42:09",
      targetCaptureId: "checkout-desktop",
      targetLabel: "Checkout · Desktop",
    },
  ],
};
